### ISSUE TITLE
Extending an Abstract Class fails

### ISSUE THREAD

**Issue by PaulJPhilp** [pkl-community/pkl-typescript#18]
I am trying to extend an abstract class:

abstract class Event {
  `type`: String
}

class feedbackUpdateEvent extends eventDef.Event {
    `type` = "feedbackUpdateEvent"
}

I get the following error message:
/Users/paul/projects/pkl-typescript/node_modules/@pkl-community/pkl-typescript/src/evaluator/evaluator.ts:97
      throw new Error(resp.error)
            ^

Error: –– Pkl Error ––
Cannot find property `typescriptPackage` in object of type `pkl.typescript.internal.TypescriptMapping#Class`.

127 | superClass.type.render(classInfo.typescriptPackage)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
at pkl.typescript.internal.ClassGen#interface[#2] (file:///Users/paul/projects/pkl-typescript/node_modules/@pkl-community/pkl-typescript/codegen/src/internal/ClassGen.pkl)

Did you mean any of the following?
typescriptModule
typescriptModuleShort
type

**Comment by jasongwartz** [comment]
Thanks for the bug report, @PaulJPhilp !

Should be resolved by: https://github.com/pkl-community/pkl-typescript/pull/19

**Comment by jasongwartz** [comment]
Would you mind trying the latest commit from main, and see if it resolves the issue?

**Comment by PaulJPhilp** [comment]
I took Abstract Classes out for a drive today.  They work great.  Thank you!
