### ISSUE TITLE
Question about readiness of the repository

### ISSUE THREAD

**Issue by nguyen-vo** [pkl-community/pkl-typescript#3]
First I wanted to thank you for working on this.

When I first saw the PKL I was really excited and wanted to test it out. In my project, I am looking to use PKL to generate Firestore documents and maintain them with Terraform. As all of my interfaces are in TS, I am curious about the state of the project and when will it be ready for use. 

If possible do you mind creating a README for a beta version?

**Comment by jasongwartz** [comment]
Hey @nguyen-vo , thanks for your interest!

I'm trying to pick back up some momentum on this after a bit of a pause. @jackkleeman has done a great job with the Evaluator part of the API, so if you just want to load Pkl into runtime objects I suppose you could do that already. But I agree with you, I'm very interested in putting this together with TS interfaces for compile-time safety.

I'm making some progress on the codegen side - I'm currently working on the CLI and generator library. I'm hoping to put up a PR with the beginnings of this shortly.

The lack of README reflects the current state of readiness, I'm afraid. 😛  I'd like to land the codegen and CLI, and get it working for basic schemas with documented limitations. Then we can iterate to support more complex schemas and get some feedback. When we have an alpha version ready for people to experiment with, we'll add a README and some examples.

If you want to keep up with us in more like real-time (and to find out when we're ready for testing), come join the `#bindings-typescript` channel on [the Pkl community Discord](https://pkl-playground.vercel.app/discord-invite). 🙏

**Comment by nguyen-vo** [comment]
@jasongwartz thank you for the quick response

With that, I will close the issue and come join the discord channel.

Thanks for all the hard work!!
